# Load in the necessary libraries

In [2]:
import requests
from bs4 import BeautifulSoup as bs 
import re

# Load our webpage

In [3]:
r = requests.get("https://www.nfl.com/stats/team-stats/")

In [4]:
soup = bs(r.content)

In [5]:
# print(soup.prettify())

In [6]:
table = soup.select('table.d3-o-table')[0]
# print(get_table.prettify())

# Scrape all the column name from the table

In [7]:
thead = table.find('thead').find_all('th')
column_header = [c.get_text() for c in thead]
column_header

['Team',
 'Att',
 'Cmp',
 'Cmp %',
 'Yds/Att',
 'Pass Yds',
 'TD',
 'INT',
 'Rate',
 '1st',
 '1st%',
 '20+',
 '40+',
 'Lng',
 'Sck',
 'SckY']

# Scrape all the rows from the table

In [8]:
tbody = table.find('tbody').find_all('tr')
list = []
for tr in tbody:
    td = tr.find_all('td')
    data =[td.get_text() for td in td]
    list.append(data)
list[0]

['BuccaneersBuccaneers',
 '751',
 '499',
 '66.4',
 '6.3',
 '4746',
 '26',
 '10',
 '89.8',
 '240',
 '32',
 '50',
 '8',
 '63T',
 '22',
 '160']

# Load the table into a DataFrame

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(list,columns = column_header )
df.head(3)

,Team,Att,Cmp,Cmp %,Yds/Att,Pass Yds,TD,INT,Rate,1st,1st%,20+,40+,Lng,Sck,SckY
0,BuccaneersBuccaneers,751,499,66.4,6.3,4746,26,10,89.8,240,32,50,8,63T,22,160
1,ChargersChargers,711,485,68.2,6.7,4791,26,10,93.3,232,32.6,50,7,55,39,207
2,VikingsVikings,672,448,66.7,7.2,4818,30,15,93.1,244,36.3,50,10,66,47,334

In [11]:
tbody = table.find('tbody').find_all('tr')
def get_team_name(name):
    if name.find('div'):
        return [team.get_text() for team in name.select('div.d3-o-club-fullname')]
    else:
        return name.get_text()
    
list = []
for tr in tbody:
    td = tr.find_all('td')
    data =[get_team_name(td) for td in td]
    list.append(data)
# list

df = pd.DataFrame(list,columns = column_header)
df

,Team,Att,Cmp,Cmp %,Yds/Att,Pass Yds,TD,INT,Rate,1st,1st%,20+,40+,Lng,Sck,SckY
0,[Buccaneers],751,499,66.4,6.3,4746,26,10,89.8,240,32,50,8,63T,22,160
1,[Chargers],711,485,68.2,6.7,4791,26,10,93.3,232,32.6,50,7,55,39,207
2,[Vikings],672,448,66.7,7.2,4818,30,15,93.1,244,36.3,50,10,66,47,334
3,[Cardinals],664,433,65.2,6,3966,17,17,79.2,189,28.5,40,3,77,46,340
4,[Chiefs],651,435,66.8,8.1,5250,41,12,104.7,272,41.8,73,13,67,26,188
5,[Jets],627,357,56.9,6.4,4040,15,14,75,191,30.5,47,10,79,42,317
6,[Bengals],610,418,68.5,7.4,4520,35,12,101,221,36.2,54,10,60T,44,280
7,[Colts],604,398,65.9,6.4,3854,17,20,79.2,193,32,41,4,49,60,422
8,[Jaguars],596,394,66.1,7,4148,25,9,93.9,208,34.9,55,3,59T,28,189
9,[Lions],588,383,65.1,7.6,4444,29,7,99.3,228,38.8,57,12,81,24,163
10,[Raiders],586,359,61.3,7.1,4182,28,17,86.7,193,32.9,58,10,60T,35,248
11,[Dolphins],584,368,63,8.2,4765,30,15,95,220,37.7,62,14,84T,35,254
12,[Texans],579,352,60.8,6.3,3642,20,19,76.8,159,27.5,55,7,58T,38,298
13,[Bills],574,361,62.9,7.5,4291,35,14,95.8,212,36.9,51,12,98T,33,162
14,[Seahawks],573,399,69.6,7.5,4282,30,12,100,206,36,50,6,54,46,348
15,[Broncos],571,345,60.4,7,4007,18,15,81.2,166,29.1,55,12,67T,63,415
16,[Steelers],571,364,63.8,6.4,3661,12,14,78.7,189,33.1,44,3,57T,38,250
17,[Packers],563,364,64.6,6.9,3890,27,12,91.9,186,33,55,7,63,32,258
18,[Cowboys],556,355,63.8,7,3911,28,18,87.9,194,34.9,50,5,68T,27,175
19,[Commanders],554,344,62.1,6.8,3783,24,16,84.7,184,33.2,46,10,75T,48,311
20,[Browns],540,335,62,6.9,3710,19,12,84.9,182,33.7,44,5,55T,44,266
21,[Patriots],540,358,66.3,7.1,3815,19,14,87.7,166,30.7,57,9,53T,41,279
22,[Eagles],536,350,65.3,8.1,4364,25,9,99,195,36.4,63,13,78T,44,259
23,[Rams],531,347,65.4,6.6,3506,16,15,82.3,181,34.1,38,4,75T,59,398
24,[Giants],520,346,66.5,6.6,3431,17,6,91.1,170,32.7,28,5,65,49,274
25,[Saints],512,338,66,7.8,3969,24,14,93.6,181,35.4,45,13,68T,38,277
26,[49ers],512,338,66,7.9,4049,30,9,102.2,188,36.7,56,6,57,31,193
27,[Ravens],488,300,61.5,6.6,3202,19,13,82.5,149,30.5,33,6,75T,38,162
28,[Panthers],457,267,58.4,7.1,3246,16,13,80.2,138,30.2,49,12,75,36,250
29,[Titans],456,285,62.5,7.1,3227,16,11,85.3,153,33.6,41,11,69T,49,313
30,[Falcons],415,257,61.9,7,2927,17,9,87.7,148,35.7,37,5,75T,37,228
31,[Bears],377,223,59.2,6.9,2598,19,15,80.3,109,28.9,38,7,56,58,379